version: 1.0.{build}
image: Visual Studio 2019
before_build:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")

    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
    }

    else

    {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
    }


    nuget restore src/WinDynamicDesktop.sln
build:
  verbosity: minimal